// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPxDUpOaRne_RTuazMH1Uye1Bq2lPzGa8',
    appId: '1:192284839774:web:fc894aca74396e3b9289cf',
    messagingSenderId: '192284839774',
    projectId: 'controliot-8aaa1',
    authDomain: 'controliot-8aaa1.firebaseapp.com',
    databaseURL: 'https://controliot-8aaa1-default-rtdb.firebaseio.com',
    storageBucket: 'controliot-8aaa1.appspot.com',
    measurementId: 'G-JS155CFG74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByX6MO--TijdUmUHKDttumd4teYFVT4dA',
    appId: '1:192284839774:android:0800f241108579a39289cf',
    messagingSenderId: '192284839774',
    projectId: 'controliot-8aaa1',
    databaseURL: 'https://controliot-8aaa1-default-rtdb.firebaseio.com',
    storageBucket: 'controliot-8aaa1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO6SBhFJ1YK-HddJ-_eCFfjhEXUuPoP8Y',
    appId: '1:192284839774:ios:b40e85e2be2b99929289cf',
    messagingSenderId: '192284839774',
    projectId: 'controliot-8aaa1',
    databaseURL: 'https://controliot-8aaa1-default-rtdb.firebaseio.com',
    storageBucket: 'controliot-8aaa1.appspot.com',
    androidClientId: '192284839774-8on1s3q733sequk5r67grmgnbbqir3et.apps.googleusercontent.com',
    iosClientId: '192284839774-u6k1vv4dh09tcl333i3kvrerimtqo6qd.apps.googleusercontent.com',
    iosBundleId: 'com.example.iotcontrol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO6SBhFJ1YK-HddJ-_eCFfjhEXUuPoP8Y',
    appId: '1:192284839774:ios:0bb39a9494e1c8b39289cf',
    messagingSenderId: '192284839774',
    projectId: 'controliot-8aaa1',
    databaseURL: 'https://controliot-8aaa1-default-rtdb.firebaseio.com',
    storageBucket: 'controliot-8aaa1.appspot.com',
    androidClientId: '192284839774-8on1s3q733sequk5r67grmgnbbqir3et.apps.googleusercontent.com',
    iosClientId: '192284839774-a3mjolp6g1mli5g2g9gnt3kjgir438pm.apps.googleusercontent.com',
    iosBundleId: 'com.example.iotcontrol.RunnerTests',
  );
}
